// flow-typed signature: dba5e3046b0b03cec3e21f0336e39bdf
// flow-typed version: <<STUB>>/pusher_v^1.5.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pusher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pusher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pusher/examples/webhook_endpoint' {
  declare module.exports: any;
}

declare module 'pusher/lib/auth' {
  declare module.exports: any;
}

declare module 'pusher/lib/config' {
  declare module.exports: any;
}

declare module 'pusher/lib/errors' {
  declare module.exports: any;
}

declare module 'pusher/lib/events' {
  declare module.exports: any;
}

declare module 'pusher/lib/notification_client' {
  declare module.exports: any;
}

declare module 'pusher/lib/notification_config' {
  declare module.exports: any;
}

declare module 'pusher/lib/parse_cloud/request' {
  declare module.exports: any;
}

declare module 'pusher/lib/pusher_config' {
  declare module.exports: any;
}

declare module 'pusher/lib/pusher' {
  declare module.exports: any;
}

declare module 'pusher/lib/requests' {
  declare module.exports: any;
}

declare module 'pusher/lib/token' {
  declare module.exports: any;
}

declare module 'pusher/lib/util' {
  declare module.exports: any;
}

declare module 'pusher/lib/version' {
  declare module.exports: any;
}

declare module 'pusher/lib/webhook' {
  declare module.exports: any;
}

declare module 'pusher/parse' {
  declare module.exports: any;
}

declare module 'pusher/parse.webpack' {
  declare module.exports: any;
}

declare module 'pusher/tests/helpers/http_proxy' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/authenticate' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/constructor' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/create_signed_query_string' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/exports' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/for_cluster' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/for_url' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/get' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/notification_client' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/post' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/trigger' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/pusher/webhook' {
  declare module.exports: any;
}

declare module 'pusher/tests/integration/webhook' {
  declare module.exports: any;
}

declare module 'pusher/tests/remote/pusher/get' {
  declare module.exports: any;
}

declare module 'pusher/tests/remote/pusher/keepalive' {
  declare module.exports: any;
}

declare module 'pusher/tests/remote/pusher/proxy' {
  declare module.exports: any;
}

declare module 'pusher/tests/remote/pusher/trigger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pusher/examples/webhook_endpoint.js' {
  declare module.exports: $Exports<'pusher/examples/webhook_endpoint'>;
}
declare module 'pusher/lib/auth.js' {
  declare module.exports: $Exports<'pusher/lib/auth'>;
}
declare module 'pusher/lib/config.js' {
  declare module.exports: $Exports<'pusher/lib/config'>;
}
declare module 'pusher/lib/errors.js' {
  declare module.exports: $Exports<'pusher/lib/errors'>;
}
declare module 'pusher/lib/events.js' {
  declare module.exports: $Exports<'pusher/lib/events'>;
}
declare module 'pusher/lib/notification_client.js' {
  declare module.exports: $Exports<'pusher/lib/notification_client'>;
}
declare module 'pusher/lib/notification_config.js' {
  declare module.exports: $Exports<'pusher/lib/notification_config'>;
}
declare module 'pusher/lib/parse_cloud/request.js' {
  declare module.exports: $Exports<'pusher/lib/parse_cloud/request'>;
}
declare module 'pusher/lib/pusher_config.js' {
  declare module.exports: $Exports<'pusher/lib/pusher_config'>;
}
declare module 'pusher/lib/pusher.js' {
  declare module.exports: $Exports<'pusher/lib/pusher'>;
}
declare module 'pusher/lib/requests.js' {
  declare module.exports: $Exports<'pusher/lib/requests'>;
}
declare module 'pusher/lib/token.js' {
  declare module.exports: $Exports<'pusher/lib/token'>;
}
declare module 'pusher/lib/util.js' {
  declare module.exports: $Exports<'pusher/lib/util'>;
}
declare module 'pusher/lib/version.js' {
  declare module.exports: $Exports<'pusher/lib/version'>;
}
declare module 'pusher/lib/webhook.js' {
  declare module.exports: $Exports<'pusher/lib/webhook'>;
}
declare module 'pusher/parse.js' {
  declare module.exports: $Exports<'pusher/parse'>;
}
declare module 'pusher/parse.webpack.js' {
  declare module.exports: $Exports<'pusher/parse.webpack'>;
}
declare module 'pusher/tests/helpers/http_proxy.js' {
  declare module.exports: $Exports<'pusher/tests/helpers/http_proxy'>;
}
declare module 'pusher/tests/integration/pusher/authenticate.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/authenticate'>;
}
declare module 'pusher/tests/integration/pusher/constructor.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/constructor'>;
}
declare module 'pusher/tests/integration/pusher/create_signed_query_string.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/create_signed_query_string'>;
}
declare module 'pusher/tests/integration/pusher/exports.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/exports'>;
}
declare module 'pusher/tests/integration/pusher/for_cluster.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/for_cluster'>;
}
declare module 'pusher/tests/integration/pusher/for_url.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/for_url'>;
}
declare module 'pusher/tests/integration/pusher/get.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/get'>;
}
declare module 'pusher/tests/integration/pusher/notification_client.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/notification_client'>;
}
declare module 'pusher/tests/integration/pusher/post.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/post'>;
}
declare module 'pusher/tests/integration/pusher/trigger.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/trigger'>;
}
declare module 'pusher/tests/integration/pusher/webhook.js' {
  declare module.exports: $Exports<'pusher/tests/integration/pusher/webhook'>;
}
declare module 'pusher/tests/integration/webhook.js' {
  declare module.exports: $Exports<'pusher/tests/integration/webhook'>;
}
declare module 'pusher/tests/remote/pusher/get.js' {
  declare module.exports: $Exports<'pusher/tests/remote/pusher/get'>;
}
declare module 'pusher/tests/remote/pusher/keepalive.js' {
  declare module.exports: $Exports<'pusher/tests/remote/pusher/keepalive'>;
}
declare module 'pusher/tests/remote/pusher/proxy.js' {
  declare module.exports: $Exports<'pusher/tests/remote/pusher/proxy'>;
}
declare module 'pusher/tests/remote/pusher/trigger.js' {
  declare module.exports: $Exports<'pusher/tests/remote/pusher/trigger'>;
}
